services:
  postgres:
    container_name: postgres-bodybuilding-diary
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: bodybuilding_diary
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - bodybuilding-diary
    restart: unless-stopped

networks:
  bodybuilding-diary:
    driver: bridge

volumes:
  postgres:
    driver: local