spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bodybuilding_diary
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:changelog.xml
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: dev
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: eyJhbGciOiJIUzI1NiJ9wew0KICAic3ViIjogIjEyMzQ1Njc4OTAiLA0KICAibmFtZSI6ICJBbmlzaCBOYXRoIiwNCiAgImlhdCI6IDE1MTYyMzkwMjINCn0xgUOHF8RobX1ILjEDfzvRHCtLdche2w92qYKtvLrL9bI
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 8080