spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bodybuilding_diary
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:changelog.xml
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect